#!/usr/bin/python
# MINIBATCH_SIZE = 1 
REAL_BATCH_SIZE = 32
BATCH_SIZE = 1000
SEQUENCE_BEFORE = 70 
SEQUENCE_AFTER = 70 
SEQUENCE_LEN = SEQUENCE_BEFORE + SEQUENCE_AFTER + 1

POWER = 0.5
CONVERGE = 1
LEARNING_RATE = 0.1

TRAINING_TIME = 60 * 60 * 2 
TEST_PERCENT = 0.05
